kind: pipeline
type: docker
name: docs-ci

trigger:
  event:
    - push
    - pull_request
    - custom

steps:
  - name: test-mkdocs-build
    image: python:3.11
    commands:
      - pip install mkdocs mkdocs-material
      - mkdocs build --strict

  - name: codespell
    image: python:3.11
    commands:
      - pip install codespell
      - codespell docs/ --ignore-words-list="nd,te"

  - name: links-check
    image: lycheeverse/lychee
    commands:
      - lychee --verbose --no-progress --timeout 20 --max-concurrency 4 'docs/**/*.md'

  - name: notify n8n
    image: curlimages/curl
    when:
      status:
        - success
        - failure
    commands:
      - |
        JSON_PAYLOAD=$(printf '{"repo":"%s","branch":"%s","status":"%s","buildUrl":"%s"}' \\
          "${DRONE_REPO}" \\
          "${DRONE_BRANCH}" \\
          "${DRONE_BUILD_STATUS}" \\
          "${DRONE_BUILD_LINK}")
        
        # For debugging, you can uncomment the next line to see the payload
        echo "Sending payload: $JSON_PAYLOAD"

        curl -X POST "https://n8n.ispnet.work/webhook/drone-build-complete" \\
        -H "Content-Type: application/json" \\
        -d "$JSON_PAYLOAD"